lib/burp_web/router.ex
defmodule BurpWeb.Router do
  use BurpWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers, %{"permissions-policy" => "interest-cohort=()"}

    plug BurpWeb.Plug.CurrentUser
    plug BurpWeb.Plug.CurrentBlog
    plug BurpWeb.Plug.SetLocale
  end

  pipeline :require_login do
    plug BurpWeb.Plug.EnsureAuthenticated
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/admin", as: :admin, alias: BurpWeb.Admin do
    pipe_through [:browser, :require_login]

    resources "/posts", PostController, except: [:show]
    resources "/comments", CommentController, except: [:show, :new, :create]
    resources "/media", MediumController, except: [:show]

    get "/config", ConfigController, :edit
    put "/config", ConfigController, :update
  end

  scope "/", BurpWeb do
    # Use the default browser stack
    pipe_through :browser

    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete

    get "/media/:slug", MediumController, :show

    get "/", PostController, :index

    get "/tags", TagController, :index
    get "/tags/:tag", TagController, :show

    get "/feed.atom", PostController, :index_atom
    get "/feed.rss", PostController, :index_rss
    get "/rss-feed", PostController, :redirect_rss
    get "/atom-feed", PostController, :redirect_atom

    get "/archive", ArchiveController, :years
    get "/:year", ArchiveController, :months
    get "/:year/:mon", ArchiveController, :index

    get "/:year/:mon/:slug", PostController, :show
    post "/:year/:mon/:slug", CommentController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", BurpWeb do
  #   pipe_through :api
  # end
end

lib/burp_web/views/layout_view.ex
defmodule BurpWeb.LayoutView do
  use BurpWeb, :view

  def page_author(_conn, %{post: post}) when not is_nil(post), do: post.author.name
  def page_author(_conn, %{current_blog: blog}) when not is_nil(blog), do: blog.author.name
  def page_author(_conn, _assigns), do: "Christian Kruse"

  def page_description(_conn, %{post: %{excerpt: excerpt}})
      when not is_nil(excerpt) and excerpt != "",
      do: excerpt

  def page_description(_conn, %{current_blog: blog}) when not is_nil(blog), do: blog.description
  def page_description(_conn, _assigns), do: gettext("Who knows Wayne?")

  def page_keywords(_conn, %{post: %{tags: tags}}) when not is_nil(tags) and tags != [] do
    tags
    |> Enum.map(& &1.tag_name)
    |> Enum.join(", ")
  end

  def page_keywords(_conn, %{current_blog: %{keywords: keywords}})
      when not is_nil(keywords) and keywords != "",
      do: keywords

  def page_keywords(_conn, _assigns), do: "wayne, ck, christian, kruse"

  def page_title(conn, assigns) do
    try do
      apply(view_module(conn), :page_title, [action_name(conn), assigns])
    rescue
      UndefinedFunctionError -> default_page_title(conn, assigns)
      FunctionClauseError -> default_page_title(conn, assigns)
    end
  end

  def default_page_title(_conn, %{post: %{subject: subject}})
      when not is_nil(subject) and subject != "",
      do: subject

  def default_page_title(conn, %{current_blog: blog} = assigns) when not is_nil(blog),
    do: "#{h1(conn, assigns)} — #{blog.name}"

  def default_page_title(_conn, _assigns), do: gettext("Who knows Wayne?")

  def h1(_conn, %{current_blog: nil}), do: gettext("Who knows Wayne?")
  def h1(_conn, %{current_blog: blog}), do: blog.name

  def subnav(conn, assigns) do
    # try do
    apply(view_module(conn), :subnav, [action_name(conn), conn, assigns])
    # rescue
    # UndefinedFunctionError -> false
    # FunctionClauseError -> false
    # end
  end

  def has_subnav?(conn, assigns) do
    try do
      apply(view_module(conn), :has_subnav?, [action_name(conn), assigns])
    rescue
      _ -> false
    end
  end

  def include_js?(conn) do
    controller_module(conn) in [
      BurpWeb.PostController,
      BurpWeb.Admin.CommentController,
      BurpWeb.Admin.PostController,
      BurpWeb.Admin.MediumController
    ]
  end
end

lib/burp_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="<%= if assigns[:current_blog], do: @current_blog.lang, else: Gettext.get_locale(BurpWeb.Gettext) %>" prefix="og: http://ogp.me/ns#">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="<%= page_description(@conn, assigns) %>">
    <meta name="author" content="<%= page_author(@conn, assigns) %>">
    <meta name="keywords" content="<%= page_keywords(@conn, assigns) %>">

    <link rel="alternate" type="application/rss+xml" title="RSS" href="<%= Routes.post_path(@conn, :index_rss) %>">
    <link rel="alternate" type="application/atom+xml" title="Atom" href="<%= Routes.post_path(@conn, :index_atom) %>">

    <link rel="shortcut icon" href="<%= Routes.static_path(@conn, "/images/favicon.png") %>">

    <title><%= page_title(@conn, assigns) %></title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>">

    <meta property="og:title" content="<%= page_title(@conn, assigns) %>">
    <meta property="og:description" content="<%= page_description(@conn, assigns) %>">
    <meta property="og:type" content="<%= if assigns[:post], do: "article", else: "website" %>">
    <%= if assigns[:post] do %>
      <meta property="article:published_time" content="<%= WebHelpers.iso_date(@post.published_at) %>">
      <meta property="article:modified_time" content="<%= WebHelpers.iso_date(@post.updated_at) %>">
      <meta property="article:author" content="<%= @post.author.name %>">
      <meta property="article:tag" content="<%= page_keywords(@conn, assigns) %>">
    <% end %>
  </head>

  <body>
    <header id="site-header">
      <%= if assigns[:current_blog] && !Helpers.blank?(@current_blog.image_url) do %>
        <div class="logo"><img src="<%= @current_blog.image_url %>" alt=""></div>
      <% end %>
      <div>
        <h1><%= link h1(@conn, assigns), to: Routes.post_path(@conn, :index) %></h1>
        <p><%= if assigns[:current_blog], do: @current_blog.description, else: gettext("Nobody cares what is written here…") %></p>
      </div>
    </header>

    <main role="main">
      <%= if has_subnav?(@conn, assigns) do %>
        <nav class="btn-toolbar" role="toolbar">
          <%= subnav(@conn, assigns) %>
        </nav>
      <% end %>

      <%= if get_flash(@conn, :info) do %><p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p><% end %>
      <%= if get_flash(@conn, :error) do %><p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p><% end %>

      <%= @inner_content %>
    </main>

    <footer>
      <p class="admin-nav">
        <%= if assigns[:current_user] do %>
          <%= link gettext("Logout"), to: Routes.session_path(@conn, :delete), rel: "nofollow" %>
          <%= link gettext("Administration"), to: Routes.admin_post_path(@conn, :index) %>
        <% else %>
          <%= link gettext("Login"), to: Routes.session_path(@conn, :new), rel: "nofollow" %>
        <% end %>
      </p>

      <nav id="site-nav"><%= gettext("Look at") %> <%= gettext("a list of") %> <%= link gettext("tags"), to: Routes.tag_path(@conn, :index) %> <%= gettext("or") %> <%= link gettext("the archive"), to: Routes.archive_path(@conn, :years) %>.</nav>

      <p class="about">
        <%= {:safe, gettext("This is a Wayne blog, only <a href=\"http://kennst-du-wayne.de/\">Wayne is interested</a>.")} %> <%= {:safe, gettext("The Software powering this platform is CKs <a href=\"http://github.com/ckruse/Burp\">Burp</a>.")} %>
        <%= if assigns[:current_blog] do %>
          <%= gettext("%{name} is creating the content on this site.", name: @current_blog.author.name) %>
        <% end %>

        <%= {:safe, gettext("When having technical issues, contact <a href=\"mailto:christian@kruse.cool\">christian@kruse.cool</a>.")} %>
      </p>

    </footer>

    <%= if include_js?(@conn) do %>
      <script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
    <% end %>
  </body>
</html>

lib/burp_web/templates/layout/email.html.eex
<html>
  <head>
    <meta charset="utf-8">
  </head>
  <body>
    <%= @inner_content %>
  </body>
</html>

lib/burp_web/templates/layout/email.text.eex
<%= @inner_content %>